In [1]:
import pandas as pd
from rdkit import Chem

In [2]:
df = pd.read_csv('newdata/Maybridge_HitDiscover.csv')

In [3]:
df

,Plate_No,Well,Code,Catalogue_Ref,molformula,molweight,Product_name,SMILES,PARENT_MW,salts,casno
0,HD40001,A02,AC10018,AC10018SC,C17 H18 F2 N2,288.3392,1-[bis(4-fluorophenyl)methyl]piperazine,FC1=CC=C(C=C1)C(C2=CC=C(F)C=C2)N3CCNCC3,288.34,NaN,27469-60-9
1,HD40001,A03,AC12157,AC12157SC,C10 H9 N O,159.1871,4-methyl-2-quinolinol,NC1=NC(N=CN2)=C2C(SC)=N1,159.20,NaN,607-66-9
2,HD40001,A04,AC13917,AC13917SC,C11 H16 N2 . 2 Cl H,249.1832,1-(2-methylphenyl)piperazine dihydrochloride,CN(C)CC1=CNC2=C1C=C(C=C2)OCC3=CC=CC=C3,176.30,2 HCl,70849-60-4
3,HD40001,A05,AC27191,AC27191SC,C9 H9 N3 O,175.1901,"5,7-dimethylpyrido[2,3-d]pyrimidin-4(3H)-one",O=C(O)C1=CC=C(Br)O1,175.19,NaN,1913-72-0
4,HD40001,A06,AC29806,AC29806SC,C7 H8 N6 O . Cl H,246.6600,"(2,4-diaminopteridin-6-yl)methanol hydrochlori...",O=C(O)C(N)CC1=CNC2=C1C=C(Br)C=C2,192.18,HCl; hydrate,73978-41-3
...,...,...,...,...,...,...,...,...,...,...,...
51770,HD40652,H07,S14814,S14814SC,C13 H10 N2 O,210.2350,2-[4-(allyloxy)benzylidene]malononitrile,O=[N+]([O-])C1=C(O/N=C(C)/OCC)C=CC([N+]([O-])=...,210.23,NaN,NaN
51771,HD40652,H08,S14839,S14839SC,C19 H16 Cl2 N4 O2 S,435.3330,"N1-[4-acetyl-5-(4-chlorophenyl)-4,5-dihydro-1,...",O=C(N1OC2=CC=C([N+]([O-])=O)C([N+]([O-])=O)=C2...,435.33,NaN,NaN
51772,HD40652,H09,S14896,S14896SC,C15 H13 N3 O3,283.2860,2-{[2-(2-phenylhydrazono)acetyl]amino}benzoic ...,O=[N+]([O-])C1=CC=C2N=C(C3=CC=CC=C3)C(C4=CC=CC...,283.29,NaN,NaN
51773,HD40652,H10,SPB05721,SPB05721SC,C14 H14 Cl2 N2 O3 S,361.2480,"2-[(2,6-dichlorobenzyl)thio]-6-(dimethoxymethy...",CC(N1)=C(C(OCC)=O)C(/C=C/C2=CC=CC=C2)C(C(OCC)=...,361.24,NaN,NaN
51774,HD40652,H11,S14916,S14916SC,C19 H11 Cl F N O3,355.7510,3-(2-chloro-6-fluorophenyl)-2-nitro-3H-benzo[f...,CC(N1)=C(C(OCC)=O)C(C2=CC=CC([N+]([O-])=O)=C2)...,355.75,NaN,NaN

In [4]:
sel = ['SMILES', 'Code']
df1 = df[sel]
df1

                                                  SMILES      Code
0                FC1=CC=C(C=C1)C(C2=CC=C(F)C=C2)N3CCNCC3   AC10018
1                               NC1=NC(N=CN2)=C2C(SC)=N1   AC12157
2                 CN(C)CC1=CNC2=C1C=C(C=C2)OCC3=CC=CC=C3   AC13917
3                                    O=C(O)C1=CC=C(Br)O1   AC27191
4                       O=C(O)C(N)CC1=CNC2=C1C=C(Br)C=C2   AC29806
...                                                  ...       ...
51770  O=[N+]([O-])C1=C(O/N=C(C)/OCC)C=CC([N+]([O-])=...    S14814
51771  O=C(N1OC2=CC=C([N+]([O-])=O)C([N+]([O-])=O)=C2...    S14839
51772  O=[N+]([O-])C1=CC=C2N=C(C3=CC=CC=C3)C(C4=CC=CC...    S14896
51773  CC(N1)=C(C(OCC)=O)C(/C=C/C2=CC=CC=C2)C(C(OCC)=...  SPB05721
51774  CC(N1)=C(C(OCC)=O)C(C2=CC=CC([N+]([O-])=O)=C2)...    S14916

[51775 rows x 2 columns]

In [5]:
def to_canonical(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol:
        return Chem.MolToSmiles(mol, isomericSmiles=True)
    else:
        return None

In [6]:
smiles_list = df1['SMILES']

canonical_smiles_list = [to_canonical(smiles) for smiles in smiles_list]

df1.loc[:, 'SMILES'] = canonical_smiles_list

[06:01:09] SMILES Parse Error: syntax error while parsing: {\rtf1\fbidis\ansi\ansicpg1252\deff0\deflang2057{\fonttbl{\f0\fswiss\fprq2\fcharset0
[06:01:09] SMILES Parse Error: Failed parsing SMILES '{\rtf1\fbidis\ansi\ansicpg1252\deff0\deflang2057{\fonttbl{\f0\fswiss\fprq2\fcharset0' for input: '{\rtf1\fbidis\ansi\ansicpg1252\deff0\deflang2057{\fonttbl{\f0\fswiss\fprq2\fcharset0'
[06:01:09] SMILES Parse Error: syntax error while parsing: O[C@H]([C@@H]1O)[C@@H]2[C@H](CO)O[C@H]1O[C@H](C(O)[C@@H]3O)[C@H](CO)O[C@H]3O[C@@H]([C@@H](O)[C@H]4O)[C@@H](CO)OC4O[C@@H]([C@@H](O)[C@H]5O)[C@@H](CO)OC5O[C@H]6C(O)[C@@H](O)[C@H](O[C@@H]6CO)O[C@H]7[C@@H](O)[C@@H](O)C(O[C@@H]7CO)O[C@@H]8[C@H](O)[C@H](O)C(O[C
[06:01:09] SMILES Parse Error: Failed parsing SMILES 'O[C@H]([C@@H]1O)[C@@H]2[C@H](CO)O[C@H]1O[C@H](C(O)[C@@H]3O)[C@H](CO)O[C@H]3O[C@@H]([C@@H](O)[C@H]4O)[C@@H](CO)OC4O[C@@H]([C@@H](O)[C@H]5O)[C@@H](CO)OC5O[C@H]6C(O)[C@@H](O)[C@H](O[C@@H]6CO)O[C@H]7[C@@H](O)[C@@H](O)C(O[C@@H]7CO)O[C@@H]8[C@H](O)[C@H](O)C(O[C' for input: 'O[C@H]([C@@H]1O)[C@@H]2[C@H](CO)O[C@H]1O[C@H](C(O)[C@@H]3O)[C@H](CO)O[C@H]3O[C@@H]([C@@H](O)[C@H]4O)[C@@H](CO)OC4O[C@@H]([C@@H](O)[C@H]5O)[C@@H](CO)OC5O[C@H]6C(O)[C@@H](O)[C@H](O[C@@H]6CO)O[C@H]7[C@@H](O)[C@@H](O)C(O[C@@H]7CO)O[C@@H]8[C@H](O)[C@H](O)C(O[C'
<ipython-input-6-f499611d4bbd>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.loc[:, 'SMILES'] = canonical_smiles_list

In [7]:
df1

                                                  SMILES      Code
0                      Fc1ccc(C(c2ccc(F)cc2)N2CCNCC2)cc1   AC10018
1                                  CSc1nc(N)nc2nc[nH]c12   AC12157
2                     CN(C)Cc1c[nH]c2ccc(OCc3ccccc3)cc12   AC13917
3                                      O=C(O)c1ccc(Br)o1   AC27191
4                        NC(Cc1c[nH]c2ccc(Br)cc12)C(=O)O   AC29806
...                                                  ...       ...
51770     CCO/C(C)=N/Oc1ccc([N+](=O)[O-])cc1[N+](=O)[O-]    S14814
51771  O=C1c2ccccc2C(=O)N1Oc1ccc([N+](=O)[O-])c([N+](...    S14839
51772   O=[N+]([O-])c1ccc2nc(-c3ccccc3)c(-c3ccccc3)nc2c1    S14896
51773    CCOC(=O)C1=C(C)NC(C)=C(C(=O)OCC)C1/C=C/c1ccccc1  SPB05721
51774  CCOC(=O)C1=C(C)NC(C)=C(C(=O)OCC)C1c1cccc([N+](...    S14916

[51775 rows x 2 columns]

In [ ]:
df1 = df1[df1.SMILES.notna()]
df1

In [22]:
df1.to_csv('maybridge/Maybridge.smi', sep='\t', index=False, header=False)

In [23]:
df1.to_csv('maybridge/Maybridge.csv', index=False, header=True)

In [ ]:
maybridge_fingerprint = pd.read_csv('maybridge/out.csv', index_col = 0)

In [4]:
smiles_list = df['canonical_smiles']

In [9]:
import numpy as np

In [10]:
df_split = np.array_split(df1, 4)

In [11]:
df_split[0].to_csv('maybridge/may1/Maybridge_1.smi', sep='\t', index=False, header=False)

In [12]:
df_split[1].to_csv('maybridge/may2/Maybridge_2.smi', sep='\t', index=False, header=False)

In [13]:
df_split[2].to_csv('maybridge/may3/Maybridge_3.smi', sep='\t', index=False, header=False)

In [14]:
df_split[3].to_csv('maybridge/may4/Maybridge_4.smi', sep='\t', index=False, header=False)

In [21]:
df1 = df1[df1.SMILES.notna()]
df1

                                                  SMILES      Code
0                      Fc1ccc(C(c2ccc(F)cc2)N2CCNCC2)cc1   AC10018
1                                  CSc1nc(N)nc2nc[nH]c12   AC12157
2                     CN(C)Cc1c[nH]c2ccc(OCc3ccccc3)cc12   AC13917
3                                      O=C(O)c1ccc(Br)o1   AC27191
4                        NC(Cc1c[nH]c2ccc(Br)cc12)C(=O)O   AC29806
...                                                  ...       ...
51770     CCO/C(C)=N/Oc1ccc([N+](=O)[O-])cc1[N+](=O)[O-]    S14814
51771  O=C1c2ccccc2C(=O)N1Oc1ccc([N+](=O)[O-])c([N+](...    S14839
51772   O=[N+]([O-])c1ccc2nc(-c3ccccc3)c(-c3ccccc3)nc2c1    S14896
51773    CCOC(=O)C1=C(C)NC(C)=C(C(=O)OCC)C1/C=C/c1ccccc1  SPB05721
51774  CCOC(=O)C1=C(C)NC(C)=C(C(=O)OCC)C1c1cccc([N+](...    S14916

[51773 rows x 2 columns]

In [20]:
finger1 = pd.read_csv('maybridge/may1/out1.csv', index_col = 0)
finger2 = pd.read_csv('maybridge/may2/out2.csv', index_col = 0)
finger3 = pd.read_csv('maybridge/may3/out3.csv', index_col = 0)
finger4 = pd.read_csv('maybridge/may4/out4.csv', index_col = 0)

,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,PubchemFP9,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
Name,,,,,,,,,,,,,,,,,,,,,
AC10018,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
AC12157,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
AC13917,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
AC27191,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
AC29806,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
JA00132,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
JA00147,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
JA00163,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
JA00014,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
JA00035,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0